format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$nodejs\
$aws\
$time\
$cmd_duration\
$line_break
$character
"""

continuation_prompt = '[â¯ ](fg:green)'

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bold #fe7f00"
symbol = ' ğŸ…° '

[character]
success_symbol = '[â¯](fg:green)'
error_symbol = '[â¯](fg:red)'

[directory]
style = "fg:blue"
format = "[$path]($style)"
truncation_length = 4
truncation_symbol = "..."
truncate_to_repo = false

[git_branch]
format = " [$symbol$branch]($style) "
style = "fg:#888888"

[git_metrics]
disabled = false
format = '\([+$added]($added_style)/[-$deleted]($deleted_style)\)'
only_nonzero_diffs = true

[line_break]
disabled = true

[package]
disabled = true

[nodejs]
style = "#ffc0cb"
format = " [$symbol$version]($style)"

[time]
disabled = false
format = 'ğŸ•™[$time]($style)'

[cmd_duration]
show_milliseconds = true
format = ' [ó±«Œ $duration]($style)'
